[Service]
Environment="DB_USERNAME=climblive"
Environment="DB_PASSWORD=climblive"
Environment="DB_HOST=localhost"
Environment="DB_PORT=3306"
Environment="DB_DATABASE=climblive"
Environment="TLS_APP_CERT_FILE=/etc/climblive/ssl/app/cert.pem"
Environment="TLS_APP_KEY_FILE=/etc/climblive/ssl/app/privkey.pem"
Environment="TLS_WWW_CERT_FILE=/etc/climblive/ssl/www/cert.pem"
Environment="TLS_WWW_KEY_FILE=/etc/climblive/ssl/www/privkey.pem"