// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type UnlockRequestStatus string

const (
	UnlockRequestStatusPending  UnlockRequestStatus = "pending"
	UnlockRequestStatusApproved UnlockRequestStatus = "approved"
	UnlockRequestStatusRejected UnlockRequestStatus = "rejected"
)

func (e *UnlockRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnlockRequestStatus(s)
	case string:
		*e = UnlockRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UnlockRequestStatus: %T", src)
	}
	return nil
}

type NullUnlockRequestStatus struct {
	UnlockRequestStatus UnlockRequestStatus
	Valid               bool // Valid is true if UnlockRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnlockRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UnlockRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnlockRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnlockRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnlockRequestStatus), nil
}

type CompClass struct {
	ID          int32
	OrganizerID int32
	ContestID   int32
	Name        string
	Description sql.NullString
	Color       sql.NullString
	TimeBegin   time.Time
	TimeEnd     time.Time
}

type Contender struct {
	ID                  int32
	OrganizerID         int32
	ContestID           int32
	RegistrationCode    string
	Name                sql.NullString
	ClassID             sql.NullInt32
	Entered             sql.NullTime
	Disqualified        bool
	WithdrawnFromFinals bool
}

type Contest struct {
	ID                 int32
	OrganizerID        int32
	Archived           bool
	SeriesID           sql.NullInt32
	Name               string
	Description        sql.NullString
	Location           sql.NullString
	QualifyingProblems int32
	Finalists          int32
	Rules              sql.NullString
	GracePeriod        int32
	Created            time.Time
	EvaluationMode     bool
}

type Organizer struct {
	ID   int32
	Name string
}

type OrganizerInvite struct {
	ID          string
	OrganizerID int32
	ExpiresAt   time.Time
}

type Problem struct {
	ID                 int32
	OrganizerID        int32
	ContestID          int32
	Number             int32
	HoldColorPrimary   string
	HoldColorSecondary sql.NullString
	Zone1Enabled       bool
	Zone2Enabled       bool
	Description        sql.NullString
	PointsZone1        sql.NullInt32
	PointsZone2        sql.NullInt32
	PointsTop          int32
	FlashBonus         sql.NullInt32
}

type Raffle struct {
	ID          int32
	OrganizerID int32
	ContestID   int32
}

type RaffleWinner struct {
	ID          int32
	OrganizerID int32
	RaffleID    int32
	ContenderID int32
	Timestamp   time.Time
}

type Score struct {
	ContenderID int32
	Timestamp   time.Time
	Score       int32
	Placement   int32
	Finalist    bool
	RankOrder   int32
}

type Series struct {
	ID          int32
	OrganizerID int32
	Name        string
}

type Tick struct {
	ID            int32
	OrganizerID   int32
	ContestID     int32
	ContenderID   int32
	ProblemID     int32
	Timestamp     time.Time
	Zone1         bool
	AttemptsZone1 int32
	Zone2         bool
	AttemptsZone2 int32
	Top           bool
	AttemptsTop   int32
}

type UnlockRequest struct {
	ID          int32
	ContestID   int32
	OrganizerID int32
	Status      UnlockRequestStatus
	CreatedAt   time.Time
	ReviewedAt  sql.NullTime
}

type User struct {
	ID       int32
	Username string
	Admin    bool
}

type UserOrganizer struct {
	UserID      int32
	OrganizerID int32
}
