// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type CompClass struct {
	ID          int32
	OrganizerID int32
	ContestID   int32
	Name        string
	Description sql.NullString
	Color       sql.NullString
	TimeBegin   time.Time
	TimeEnd     time.Time
}

type Contender struct {
	ID                  int32
	OrganizerID         int32
	ContestID           int32
	RegistrationCode    string
	Name                sql.NullString
	Club                sql.NullString
	ClassID             sql.NullInt32
	Entered             sql.NullTime
	Disqualified        bool
	WithdrawnFromFinals bool
}

type Contest struct {
	ID                 int32
	OrganizerID        int32
	Protected          bool
	SeriesID           sql.NullInt32
	Name               string
	Description        sql.NullString
	Location           sql.NullString
	FinalEnabled       bool
	QualifyingProblems int32
	Finalists          int32
	Rules              sql.NullString
	GracePeriod        int32
}

type Organizer struct {
	ID       int32
	Name     string
	Homepage sql.NullString
}

type Problem struct {
	ID                 int32
	OrganizerID        int32
	ContestID          int32
	Number             int32
	HoldColorPrimary   string
	HoldColorSecondary sql.NullString
	Name               sql.NullString
	Description        sql.NullString
	Points             int32
	FlashBonus         sql.NullInt32
}

type Raffle struct {
	ID          int32
	OrganizerID int32
	ContestID   int32
	Active      bool
}

type RaffleWinner struct {
	ID          int32
	OrganizerID int32
	RaffleID    int32
	ContenderID int32
	Timestamp   time.Time
}

type Score struct {
	ContenderID int32
	Timestamp   time.Time
	Score       int32
	Placement   int32
	Finalist    bool
	RankOrder   int32
}

type Series struct {
	ID          int32
	OrganizerID int32
	Name        string
}

type Tick struct {
	ID          int32
	OrganizerID int32
	ContestID   int32
	ContenderID int32
	ProblemID   int32
	Flash       bool
	Timestamp   time.Time
}

type User struct {
	ID       int32
	Name     string
	Username string
	Admin    bool
}

type UserOrganizer struct {
	UserID      int32
	OrganizerID int32
}
