// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CompClass struct {
	ID          uuid.UUID
	OrganizerID uuid.UUID
	ContestID   uuid.UUID
	Name        string
	Description sql.NullString
	Color       sql.NullString
	TimeBegin   time.Time
	TimeEnd     time.Time
}

type Contender struct {
	ID                  uuid.UUID
	OrganizerID         uuid.UUID
	ContestID           uuid.UUID
	RegistrationCode    string
	Name                sql.NullString
	ClassID             uuid.NullUUID
	Entered             sql.NullTime
	Disqualified        bool
	WithdrawnFromFinals bool
}

type Contest struct {
	ID                 uuid.UUID
	OrganizerID        uuid.UUID
	Archived           bool
	SeriesID           uuid.NullUUID
	Name               string
	Description        sql.NullString
	Location           sql.NullString
	QualifyingProblems int32
	Finalists          int32
	Info               sql.NullString
	GracePeriod        int32
	Created            time.Time
}

type Organizer struct {
	ID   uuid.UUID
	Name string
}

type OrganizerInvite struct {
	ID          string
	OrganizerID uuid.UUID
	ExpiresAt   time.Time
}

type Problem struct {
	ID                 uuid.UUID
	OrganizerID        uuid.UUID
	ContestID          uuid.UUID
	Number             int32
	HoldColorPrimary   string
	HoldColorSecondary sql.NullString
	Zone1Enabled       bool
	Zone2Enabled       bool
	Description        sql.NullString
	PointsZone1        sql.NullInt32
	PointsZone2        sql.NullInt32
	PointsTop          int32
	FlashBonus         sql.NullInt32
}

type Raffle struct {
	ID          uuid.UUID
	OrganizerID uuid.UUID
	ContestID   uuid.UUID
}

type RaffleWinner struct {
	ID          uuid.UUID
	OrganizerID uuid.UUID
	RaffleID    uuid.UUID
	ContenderID uuid.UUID
	Timestamp   time.Time
}

type Score struct {
	ContenderID uuid.UUID
	Timestamp   time.Time
	Score       int32
	Placement   int32
	Finalist    bool
	RankOrder   int32
}

type Series struct {
	ID          uuid.UUID
	OrganizerID uuid.UUID
	Name        string
}

type Tick struct {
	ID            uuid.UUID
	OrganizerID   uuid.UUID
	ContestID     uuid.UUID
	ContenderID   uuid.UUID
	ProblemID     uuid.UUID
	Timestamp     time.Time
	Zone1         bool
	AttemptsZone1 int32
	Zone2         bool
	AttemptsZone2 int32
	Top           bool
	AttemptsTop   int32
}

type User struct {
	ID       uuid.UUID
	Username string
	Admin    bool
}

type UserOrganizer struct {
	UserID      uuid.UUID
	OrganizerID uuid.UUID
}
