name: "Deploy"
inputs:
  package-file-name:
    description: "Package file name"
    required: true
  deploy-host:
    description: "Deploy host"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        scp -o StrictHostKeyChecking=accept-new ${{ inputs.package-file-name }} root@${{ inputs.deploy-host }}:
        ssh -t root@${{ inputs.deploy-host }} "apt-get install -y ~/${{ inputs.package-file-name }}"
        ssh -t root@${{ inputs.deploy-host }} "systemctl daemon-reload"
        ssh -t root@${{ inputs.deploy-host }} "systemctl restart climblive2"
        ssh -t root@${{ inputs.deploy-host }} "systemctl reload nginx"
