name: "Deploy"
inputs:
  package-file-name:
    description: "Package file name"
    required: true
  deploy-host:
    description: "Deploy host"
    required: true
  deploy-ssh-key:
    description: "Deploy SSH key"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.deploy-ssh-key }}" > ~/.ssh/id_ecdsa
        chmod 400 ~/.ssh/id_ecdsa
        scp -o StrictHostKeyChecking=accept-new ${{ inputs.package-file-name }} root@${{ inputs.deploy-host }}:
        ssh -t root@${{ vars.DEPLOY_HOST }} "apt-get install -y ~/${{ inputs.package-file-name }}"
        ssh -t root@${{ vars.DEPLOY_HOST }} "systemctl daemon-reload"
        ssh -t root@${{ vars.DEPLOY_HOST }} "systemctl restart climblive2"
        ssh -t root@${{ vars.DEPLOY_HOST }} "systemctl reload nginx"
