#!/bin/bash

set -e

mkdir -p /etc/climblive
cat > /etc/climblive/environment <<EOF
DB_USERNAME=climblive
DB_PASSWORD=climblive
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=climblive
EOF

docker load -i /usr/share/climblive/climblive-api.tar