name: "Build backend"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: "backend/go.mod"

    - run: go build -o climblive cmd/api/main.go
    - shell: bash
      working-directory: backend

    - uses: actions/upload-artifact@v4
      with:
        name: backend
        path: backend/climblive
