name: "Package for Debian"
inputs:
  version:
    description: "Version"
    required: true
outputs:
  package-file-name:
    description: "Package file name"
    value: ${{ steps.build-pkg.outputs.package-file-name }}
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: backend
        path: backend

    - shell: bash
      id: build-pkg
      run: |
        mkdir -p packageroot/usr/bin
        mv backend/climblive packageroot/usr/bin
        chmod +x packageroot/usr/bin/climblive
        sed -i "s/VERSION/${{ inputs.version }}/g" packageroot/DEBIAN/control
        dpkg-deb -b packageroot .
        echo "package-file-name=climblive_${{ inputs.version }}_amd64.deb" >> $GITHUB_OUTPUT
