// Code generated by tygo. DO NOT EDIT.

//////////
// source: id.go

export type ResourceID = number /* int32 */;
export type CompClassID = ResourceID;
export type ContenderID = ResourceID;
export type ContestID = ResourceID;
export type OrganizerID = ResourceID;
export type ProblemID = ResourceID;
export type RaffleID = ResourceID;
export type RaffleWinnerID = ResourceID;
export type SeriesID = ResourceID;
export type UserID = ResourceID;
export type TickID = ResourceID;
export type ResourceIDType = 
    CompClassID | ContenderID | ContestID | OrganizerID | ProblemID | RaffleID | RaffleWinnerID | SeriesID | UserID | TickID;
export type ScoreEngineInstanceID = string;

//////////
// source: public.go

export type ColorRGB = string;
export interface OwnershipData {
  organizerId: OrganizerID;
}
export interface CompClass {
  id: CompClassID;
  contestId: ContestID;
  name: string;
  description?: string;
  timeBegin: Date;
  timeEnd: Date;
}
export interface CompClassTemplate {
  name: string;
  description?: string;
  timeBegin: Date;
  timeEnd: Date;
}
export interface CompClassPatch {
  name?: string;
  description?: string;
  timeBegin?: Date;
  timeEnd?: Date;
}
export interface Contender {
  id: ContenderID;
  contestId: ContestID;
  compClassId?: CompClassID;
  registrationCode: string;
  name?: string;
  entered?: Date;
  withdrawnFromFinals: boolean;
  disqualified: boolean;
  score?: Score;
}
export interface ContenderPatch {
  compClassId?: CompClassID;
  name?: string;
  withdrawnFromFinals?: boolean;
  disqualified?: boolean;
}
export interface Contest {
  id: ContestID;
  ownership: OwnershipData;
  location?: string;
  seriesId?: SeriesID;
  name: string;
  description?: string;
  qualifyingProblems: number /* int */;
  finalists: number /* int */;
  rules?: string;
  gracePeriod: number;
  timeBegin?: Date;
  timeEnd?: Date;
}
export interface ContestTemplate {
  location?: string;
  seriesId?: SeriesID;
  name: string;
  description?: string;
  qualifyingProblems: number /* int */;
  finalists: number /* int */;
  rules?: string;
  gracePeriod: number;
}
export interface ContestPatch {
  location?: string;
  seriesId?: number;
  name?: string;
  description?: string;
  qualifyingProblems?: number;
  finalists?: number;
  rules?: string;
  gracePeriod?: number;
}
export interface Organizer {
  id: OrganizerID;
  name: string;
}
export interface Problem {
  id: ProblemID;
  contestId: ContestID;
  number: number /* int */;
  holdColorPrimary: string;
  holdColorSecondary?: string;
  description?: string;
  zone1Enabled: boolean;
  zone2Enabled: boolean;
  pointsZone1: number /* int */;
  pointsZone2: number /* int */;
  pointsTop: number /* int */;
  flashBonus?: number /* int */;
}
export interface ProblemTemplate {
  number: number /* int */;
  holdColorPrimary: string;
  holdColorSecondary?: string;
  description?: string;
  zone1Enabled: boolean;
  zone2Enabled: boolean;
  pointsZone1: number /* int */;
  pointsZone2: number /* int */;
  pointsTop: number /* int */;
  flashBonus?: number /* int */;
}
export interface ProblemPatch {
  number?: number;
  holdColorPrimary?: string;
  holdColorSecondary?: string;
  description?: string;
  zone1Enabled?: boolean;
  zone2Enabled?: boolean;
  pointsZone1?: number;
  pointsZone2?: number;
  pointsTop?: number;
  flashBonus?: number;
}
export interface Raffle {
  id: RaffleID;
  contestId: ContestID;
}
export interface RaffleWinner {
  id: RaffleWinnerID;
  raffleId: RaffleID;
  contenderId: ContenderID;
  readonly contenderName: string;
  timestamp: Date;
}
export interface Score {
  timestamp: Date;
  contenderId: ContenderID;
  score: number /* int */;
  placement: number /* int */;
  finalist: boolean;
  rankOrder: number /* int */;
}
export interface Series {
  id: SeriesID;
  name: string;
}
export interface ScoreboardEntry {
  contenderId: ContenderID;
  compClassId: CompClassID;
  name: string;
  withdrawnFromFinals: boolean;
  disqualified: boolean;
  score?: Score;
}
export interface Tick {
  id: TickID;
  timestamp: Date;
  problemId: ProblemID;
  zone1: boolean;
  attemptsZone1: number /* int */;
  zone2: boolean;
  attemptsZone2: number /* int */;
  top: boolean;
  attemptsTop: number /* int */;
}
export interface User {
  id: UserID;
  username: string;
  admin: boolean;
  organizers: Organizer[];
}
export interface ContenderEnteredEvent {
  contenderId: ContenderID;
  compClassId: CompClassID;
}
export interface ContenderSwitchedClassEvent {
  contenderId: ContenderID;
  compClassId: CompClassID;
}
export interface ContenderWithdrewFromFinalsEvent {
  contenderId: ContenderID;
}
export interface ContenderReenteredFinalsEvent {
  contenderId: ContenderID;
}
export interface ContenderDisqualifiedEvent {
  contenderId: ContenderID;
}
export interface ContenderRequalifiedEvent {
  contenderId: ContenderID;
}
export interface AscentRegisteredEvent {
  tickId: TickID;
  timestamp: Date;
  contenderId: ContenderID;
  problemId: ProblemID;
  top: boolean;
  attemptsTop: number /* int */;
  zone: boolean;
  attemptsZone: number /* int */;
}
export interface AscentDeregisteredEvent {
  tickId: TickID;
  contenderId: ContenderID;
  problemId: ProblemID;
}
export interface ProblemAddedEvent {
  problemId: ProblemID;
  pointsTop: number /* int */;
  pointsZone: number /* int */;
  flashBonus: number /* int */;
}
export interface ProblemUpdatedEvent {
  problemId: ProblemID;
  pointsTop: number /* int */;
  pointsZone: number /* int */;
  flashBonus: number /* int */;
}
export interface ProblemDeletedEvent {
  problemId: ProblemID;
}
export interface ContenderPublicInfoUpdatedEvent {
  contenderId: ContenderID;
  compClassId: CompClassID;
  name: string;
  withdrawnFromFinals: boolean;
  disqualified: boolean;
}
export interface ContenderScoreUpdatedEvent {
  timestamp: Date;
  contenderId: ContenderID;
  score: number /* int */;
  placement: number /* int */;
  finalist: boolean;
  rankOrder: number /* int */;
}
export interface ScoreEngineStartedEvent {
  instanceId: ScoreEngineInstanceID;
}
export interface ScoreEngineStoppedEvent {
  instanceId: ScoreEngineInstanceID;
}
