// Code generated by tygo. DO NOT EDIT.

//////////
// source: public.go

export interface CreateContendersArguments {
  number: number /* int */;
}
export interface StartScoreEngineArguments {
  terminatedBy: Date;
}
