on: pull_request

jobs:
  check:
    name: Code check
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: web/package.json
      - uses: actions/setup-node@v4
        with:
          node-version-file: web/package.json
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml
      - run: pnpm --filter=* format:check
        working-directory: web
      - run: pnpm --filter=* check
        working-directory: web
      - run: pnpm --filter=* lint
        working-directory: web

  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: web/package.json
      - uses: actions/setup-node@v4
        with:
          node-version-file: web/package.json
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml
      - run: pnpm install
        working-directory: web
      - run: pnpm --filter=* build
        working-directory: web