on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.1
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'web/package.json'
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'
      - run: pnpm install
        working-directory: web
      - run: pnpm --filter=* build
        working-directory: web